[build]
builder = "NIXPACKS"

[deploy]
startCommand = "python manage.py migrate && gunicorn bszone_backend.wsgi"
healthcheckPath = "/health"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
