# Generated by Django 5.2.13 on 2026-05-04 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worklog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='worklog',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='worklog',
            name='load_type',
            field=models.CharField(blank=True, choices=[('lease load', 'Lease Load'), ('Direct Load', 'Direct Load')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='worklog',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='worklog',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='worklog',
            name='transport_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
