# Generated by Django 5.2.13 on 2026-04-26 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0002_land_agreed_emi_amount_landleasepayment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='land',
            name='agreed_emi_amount',
        ),
    ]
